"""``confluid.bake`` — build-time AST bake of ``__init__`` body-slot names.

The bake step runs the same AST scan as the runtime engine while source still
exists and emits ``<package>/_confluid_baked.py``; at runtime the engine unions
the baked names in whenever the live scan comes up empty (compiled / frozen /
zip deployments). The "frozen" condition is simulated for real here: import the
package, bake, DELETE the ``.py`` source, clear ``linecache`` — after that
``inspect.getsource`` raises exactly as in a frozen app.

Warnings are asserted via the SimpleNamespace-collector pattern (loggair is not
caplog-capturable — see the AGENTS logging mandate).
"""

import importlib
import linecache
import sys
from pathlib import Path
from types import SimpleNamespace
from typing import Any, Callable, Dict, List

import pytest

import confluid.engine as engine_module
import confluid.introspect as introspect_module
from confluid import flow, load
from confluid.bake import bake_broadcast_attrs, baked_module_path, main, render_baked_module, scan_package
from confluid.introspect import baked_init_attrs, init_source_available

_PKG_MODULE_SOURCE = '''\
from confluid import configurable


@configurable
class BakedTrainer:
    """Minimal-ctor class whose body slots the bake must capture."""

    def __init__(self, model: str = "default_model") -> None:
        self.model = model
        self.loss_fn = "default_loss"


class PlainBase:
    """NOT @configurable — in-package base classes are baked too (MRO parity)."""

    def __init__(self) -> None:
        self.base_slot = 1


class EmptyInit:
    """Empty body — bakes an EMPTY entry ("scanned, nothing found")."""

    def __init__(self) -> None:
        pass


class NoInit:
    """No own __init__ — no bake entry (the engine skips these too)."""
'''


@pytest.fixture
def pkg_factory(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Any:
    """Create importable throwaway packages under tmp_path; clean caches after.

    Package names must be unique per test (sys.modules and the baked-table
    cache are process-global); each test passes its own name.
    """
    monkeypatch.syspath_prepend(str(tmp_path))
    created: List[str] = []

    def make(name: str) -> Path:
        pkg_dir = tmp_path / name
        pkg_dir.mkdir()
        (pkg_dir / "__init__.py").write_text("")
        (pkg_dir / "mod.py").write_text(_PKG_MODULE_SOURCE)
        importlib.invalidate_caches()
        created.append(name)
        return pkg_dir

    yield make

    for name in created:
        for mod_name in [m for m in sys.modules if m == name or m.startswith(f"{name}.")]:
            sys.modules.pop(mod_name, None)
        introspect_module._baked_tables.pop(name, None)
    linecache.clearcache()


def _capture_engine_warnings(monkeypatch: pytest.MonkeyPatch) -> List[str]:
    seen: List[str] = []
    monkeypatch.setattr(
        engine_module,
        "logger",
        SimpleNamespace(
            warning=lambda msg: seen.append(msg),
            trace=lambda msg: None,
            debug=lambda msg: None,
            info=lambda msg: None,
            error=lambda msg: None,
        ),
    )
    return seen


def _freeze_package(pkg_dir: Path) -> None:
    """Simulate a frozen deployment: source gone, linecache cold, caches cleared."""
    (pkg_dir / "mod.py").unlink()
    linecache.clearcache()
    engine_module._post_init_attrs_cache.clear()
    engine_module._acceptable_keys_cache.clear()


# ---------------------------------------------------------------------------
# scan_package / render / bake — the generator
# ---------------------------------------------------------------------------


def test_scan_package_collects_every_own_init_class(pkg_factory: Callable[[str], Path]) -> None:
    pkg_factory("bakepkg_scan")
    table = scan_package("bakepkg_scan")
    assert table["bakepkg_scan.mod.BakedTrainer"] == ("loss_fn", "model")  # sorted
    assert table["bakepkg_scan.mod.PlainBase"] == ("base_slot",)  # non-configurable baked too
    assert table["bakepkg_scan.mod.EmptyInit"] == ()  # empty entry is meaningful
    assert "bakepkg_scan.mod.NoInit" not in table  # no own __init__ -> no entry


def test_bake_writes_provenance_headed_importable_module(pkg_factory: Callable[[str], Path]) -> None:
    pkg_dir = pkg_factory("bakepkg_write")
    summary = bake_broadcast_attrs(["bakepkg_write"])
    baked_path = pkg_dir / "_confluid_baked.py"
    assert baked_path.exists()
    assert summary["bakepkg_write"]["changed"] is True
    assert summary["bakepkg_write"]["path"] == str(baked_path)

    content = baked_path.read_text()
    assert "AUTO-GENERATED FILE — DO NOT EDIT BY HAND" in content
    assert "Generated by: python -m confluid.bake bakepkg_write" in content

    baked = importlib.import_module("bakepkg_write._confluid_baked")
    assert baked.BROADCAST_ATTRS == scan_package("bakepkg_write")


def test_bake_is_idempotent_and_check_detects_drift(pkg_factory: Callable[[str], Path]) -> None:
    pkg_factory("bakepkg_check")
    bake_broadcast_attrs(["bakepkg_check"])
    # Fresh re-bake and check both see no drift.
    assert bake_broadcast_attrs(["bakepkg_check"])["bakepkg_check"]["changed"] is False
    assert bake_broadcast_attrs(["bakepkg_check"], check=True)["bakepkg_check"]["changed"] is False

    # Corrupt the table: check reports drift WITHOUT rewriting.
    baked_path = baked_module_path("bakepkg_check")
    baked_path.write_text("BROADCAST_ATTRS = {}\n")
    assert bake_broadcast_attrs(["bakepkg_check"], check=True)["bakepkg_check"]["changed"] is True
    assert baked_path.read_text() == "BROADCAST_ATTRS = {}\n"  # check mode never writes


def test_main_cli_writes_and_check_exits_nonzero_on_drift(
    pkg_factory: Callable[[str], Path], capsys: pytest.CaptureFixture[str]
) -> None:
    pkg_factory("bakepkg_cli")
    assert main(["bakepkg_cli"]) == 0
    assert "bakepkg_cli" in capsys.readouterr().out
    assert main(["bakepkg_cli", "--check"]) == 0

    baked_module_path("bakepkg_cli").write_text("BROADCAST_ATTRS = {}\n")
    assert main(["bakepkg_cli", "--check"]) == 1
    assert "out of date" in capsys.readouterr().err


def test_render_is_deterministic(pkg_factory: Callable[[str], Path]) -> None:
    pkg_factory("bakepkg_det")
    table = scan_package("bakepkg_det")
    assert render_baked_module("bakepkg_det", table) == render_baked_module(
        "bakepkg_det", dict(reversed(table.items()))
    )


# ---------------------------------------------------------------------------
# Runtime consumption — baked table as the no-source fallback
# ---------------------------------------------------------------------------


def test_baked_lookup_covers_class_and_engine_unions_it_without_source(
    pkg_factory: Callable[[str], Path], monkeypatch: pytest.MonkeyPatch
) -> None:
    warnings_seen = _capture_engine_warnings(monkeypatch)
    pkg_dir = pkg_factory("bakepkg_frozen")
    mod = importlib.import_module("bakepkg_frozen.mod")
    bake_broadcast_attrs(["bakepkg_frozen"])
    _freeze_package(pkg_dir)

    # Premise: the frozen simulation is real — the live scan is blind now.
    assert init_source_available(mod.BakedTrainer.__dict__["__init__"]) is False
    # The baked table covers the class (and its in-package base).
    assert baked_init_attrs(mod.BakedTrainer) == ("loss_fn", "model")
    assert baked_init_attrs(mod.EmptyInit) == ()

    attrs = engine_module._get_post_init_attrs(mod.BakedTrainer)
    assert {"loss_fn", "model"}.issubset(attrs)
    assert warnings_seen == []  # covered -> the cannot-scan warning stays quiet


def test_end_to_end_broadcast_from_baked_table_without_source(
    pkg_factory: Callable[[str], Path], monkeypatch: pytest.MonkeyPatch
) -> None:
    warnings_seen = _capture_engine_warnings(monkeypatch)
    pkg_dir = pkg_factory("bakepkg_e2e")
    importlib.import_module("bakepkg_e2e.mod")  # registers BakedTrainer
    bake_broadcast_attrs(["bakepkg_e2e"])
    _freeze_package(pkg_dir)

    cfg = load("loss_fn: custom_loss\ntrainer: !class:BakedTrainer\n  model: my_model\n")
    trainer: Any = flow(cfg["trainer"])
    assert trainer.model == "my_model"
    assert trainer.loss_fn == "custom_loss"  # broadcast landed via the baked names
    assert warnings_seen == []


def test_unbaked_sourceless_class_still_warns_and_mentions_bake(
    pkg_factory: Callable[[str], Path], monkeypatch: pytest.MonkeyPatch
) -> None:
    warnings_seen = _capture_engine_warnings(monkeypatch)
    pkg_dir = pkg_factory("bakepkg_unbaked")
    mod = importlib.import_module("bakepkg_unbaked.mod")
    _freeze_package(pkg_dir)  # NO bake step ran

    attrs = engine_module._get_post_init_attrs(mod.BakedTrainer)
    assert "loss_fn" not in attrs  # the divergence the warning is about
    mine = [msg for msg in warnings_seen if "bakepkg_unbaked" in msg]
    assert len(mine) == 1
    assert "confluid-bake" in mine[0]
    assert "broadcast_attrs" in mine[0]


def test_stale_baked_names_do_not_override_a_readable_scan(pkg_factory: Callable[[str], Path]) -> None:
    # Source AVAILABLE: the live scan is authoritative; a (stale) baked entry
    # for a class whose scan found names is never consulted.
    pkg_factory("bakepkg_stale")
    mod = importlib.import_module("bakepkg_stale.mod")
    doctored: Dict[str, Any] = {"bakepkg_stale.mod.BakedTrainer": ("ghost_slot",)}
    baked_module_path("bakepkg_stale").write_text(f"BROADCAST_ATTRS = {doctored!r}\n")
    introspect_module._baked_tables.pop("bakepkg_stale", None)

    engine_module._post_init_attrs_cache.clear()
    attrs = engine_module._get_post_init_attrs(mod.BakedTrainer)
    assert "loss_fn" in attrs  # live scan
    assert "ghost_slot" not in attrs  # stale bake ignored while source exists


def test_baked_lookup_returns_none_without_bake_module() -> None:
    assert baked_init_attrs(dict) is None  # builtins ship no bake table


if __name__ == "__main__":
    pytest.main([__file__])
