"""Pydantic-driven validation policy for ``@configurable`` classes.

The pydantic schemas auto-generated by :func:`confluid.to_pydantic` are
enforced at three points in a class's lifecycle:

1. **``__init__``** — wrapped by the :func:`configurable` decorator. Runs on
   every direct Python instantiation of a registered class. Mode comes from
   :attr:`ValidationPolicy.init`.
2. **YAML materialization** — :func:`confluid.flow` temporarily swaps the
   active mode to :attr:`ValidationPolicy.yaml` around the ``target(**ctor)``
   call so YAML-driven runs can be configured independently of direct-Python
   instantiation.
3. **MCP tool entrypoints** — navigaitor's subprocess tool bodies call
   :func:`validate_model` on the typed pydantic config before spawning the
   subprocess. Mode comes from :attr:`ValidationPolicy.tool`.

Each mode is one of:

* ``"strict"`` (default) — pydantic ``ValidationError`` is re-raised.
* ``"warn"`` — error is logged via :mod:`logging` and execution continues
  (the downstream code may still fail naturally on the bad value).
* ``"off"`` — validation is skipped entirely; identical to pre-validation
  behaviour.

The policy is process-wide. Defaults to ``("strict", "strict", "strict")``,
overridable via env vars at first :func:`get_policy` access:

* ``CONFLUID_VALIDATE_INIT``
* ``CONFLUID_VALIDATE_YAML``
* ``CONFLUID_VALIDATE_TOOL``
"""

from __future__ import annotations

import logging
import os
from contextlib import contextmanager
from dataclasses import dataclass, replace
from typing import Any, Dict, Iterator, Literal, Optional

from pydantic import BaseModel, ValidationError

logger = logging.getLogger(__name__)


ValidationMode = Literal["strict", "warn", "off"]

_VALID_MODES: frozenset[str] = frozenset(("strict", "warn", "off"))


@dataclass(frozen=True)
class ValidationPolicy:
    """Strict/warn/off knob per validation point.

    All three default to ``"strict"`` — the safest behaviour for catching bad
    configs early. Use :func:`set_policy` (or env vars) to relax individual
    levels without touching the others.
    """

    init: ValidationMode = "strict"
    yaml: ValidationMode = "strict"
    tool: ValidationMode = "strict"


_policy: Optional[ValidationPolicy] = None


def _normalize_mode(value: str, *, env_var: str) -> ValidationMode:
    """Parse ``value`` to a ``ValidationMode``; raise on unknown literals.

    Used by the env-var reader so a typo (``CONFLUID_VALIDATE_INIT=stict``)
    surfaces loudly at startup rather than being silently treated as
    ``"strict"``.
    """
    lowered = value.strip().lower()
    if lowered not in _VALID_MODES:
        raise ValueError(
            f"{env_var}={value!r} is not a valid ValidationMode " f"(expected one of {sorted(_VALID_MODES)})"
        )
    return lowered  # type: ignore[return-value]


def _policy_from_env() -> ValidationPolicy:
    """Build a :class:`ValidationPolicy` from env vars, falling back to defaults."""
    defaults = ValidationPolicy()
    return ValidationPolicy(
        init=_normalize_mode(os.environ.get("CONFLUID_VALIDATE_INIT", defaults.init), env_var="CONFLUID_VALIDATE_INIT"),
        yaml=_normalize_mode(os.environ.get("CONFLUID_VALIDATE_YAML", defaults.yaml), env_var="CONFLUID_VALIDATE_YAML"),
        tool=_normalize_mode(os.environ.get("CONFLUID_VALIDATE_TOOL", defaults.tool), env_var="CONFLUID_VALIDATE_TOOL"),
    )


def get_policy() -> ValidationPolicy:
    """Return the active :class:`ValidationPolicy` (initialised from env vars on first use)."""
    global _policy
    if _policy is None:
        _policy = _policy_from_env()
    return _policy


def set_policy(
    *,
    init: Optional[ValidationMode] = None,
    yaml: Optional[ValidationMode] = None,
    tool: Optional[ValidationMode] = None,
) -> ValidationPolicy:
    """Replace one or more knobs on the active policy and return the new policy."""
    current = get_policy()
    updates: Dict[str, ValidationMode] = {}
    if init is not None:
        updates["init"] = init
    if yaml is not None:
        updates["yaml"] = yaml
    if tool is not None:
        updates["tool"] = tool
    if not updates:
        return current
    new_policy = replace(current, **updates)
    global _policy
    _policy = new_policy
    return new_policy


def reset_policy() -> None:
    """Drop the cached policy so the next :func:`get_policy` re-reads env vars.

    Intended for tests that mutate env vars and want a clean slate.
    """
    global _policy
    _policy = None


@contextmanager
def override_init_mode(mode: ValidationMode) -> Iterator[None]:
    """Temporarily set :attr:`ValidationPolicy.init` to ``mode``.

    Used by :func:`confluid.flow` to apply :attr:`ValidationPolicy.yaml`
    semantics during YAML materialization without permanently mutating the
    policy.
    """
    previous = get_policy()
    set_policy(init=mode)
    try:
        yield
    finally:
        global _policy
        _policy = previous


def validate_kwargs(cls: type, kwargs: Dict[str, Any], mode: ValidationMode) -> None:
    """Validate constructor kwargs against ``to_pydantic(cls)`` under ``mode``.

    Builds (or reuses the cached) pydantic mirror of ``cls.__init__`` and
    runs ``Model.model_validate(kwargs)``. On failure:

    * ``"strict"`` — re-raise the pydantic :class:`ValidationError` with a
      message that names ``cls.__name__`` so the user knows which class
      rejected the kwargs.
    * ``"warn"`` — log a warning and return so the wrapped ``__init__`` can
      proceed (it may still fail naturally on the bad value).
    * ``"off"`` — return immediately without building the schema.
    """
    if mode == "off":
        return

    # Lazy import: ``pydantic_export`` pulls pydantic + inspect, which is
    # heavier than this module needs to be eligible to import.
    from confluid.pydantic_export import to_pydantic

    try:
        model = to_pydantic(cls)
    except TypeError:
        # Class signature not introspectable (e.g. C extension without a
        # Python wrapper). Skip validation rather than blocking instantiation.
        return

    try:
        model.model_validate(kwargs)
    except ValidationError as exc:
        if mode == "strict":
            raise
        logger.warning("%s: invalid configuration\n%s", cls.__name__, exc)


def validate_setattr(cls: type, name: str, value: Any, mode: ValidationMode) -> None:
    """Validate a post-construction setattr against the field's pydantic type.

    Mirrors :func:`validate_kwargs` for the single-field case used by
    :func:`confluid.configure`. Unknown field names are silently allowed
    here (the configure path may target attributes outside the ``__init__``
    signature, e.g. ``@configurable`` classes that expose extra knobs as
    plain instance attributes).
    """
    if mode == "off":
        return

    from confluid.pydantic_export import to_pydantic

    try:
        model = to_pydantic(cls)
    except TypeError:
        return

    if name not in model.model_fields:
        return

    try:
        model.__pydantic_validator__.validate_assignment(model.model_construct(), name, value)
    except ValidationError as exc:
        if mode == "strict":
            raise
        logger.warning("%s.%s: invalid value\n%s", cls.__name__, name, exc)


def validate_model(model: BaseModel, mode: ValidationMode) -> None:
    """Re-validate an already-constructed pydantic model under ``mode``.

    Pydantic validates at construction, but navigaitor's MCP tool entry needs
    to surface ``warn`` outcomes as structured warnings without raising. This
    helper redundantly re-validates so the same mode logic applies uniformly.
    """
    if mode == "off":
        return

    try:
        type(model).model_validate(model.model_dump())
    except ValidationError as exc:
        if mode == "strict":
            raise
        logger.warning("%s: invalid configuration\n%s", type(model).__name__, exc)


__all__ = [
    "ValidationMode",
    "ValidationPolicy",
    "get_policy",
    "set_policy",
    "reset_policy",
    "override_init_mode",
    "validate_kwargs",
    "validate_setattr",
    "validate_model",
]
