"""Pydantic-driven validation policy for ``@configurable`` classes.

The pydantic schemas auto-generated by :func:`confluid.to_pydantic` are
enforced at three points in a class's lifecycle:

1. **``__init__``** — wrapped by the :func:`configurable` decorator. Runs on
   every direct Python instantiation of a registered class. Mode comes from
   :attr:`ValidationPolicy.init`.
2. **YAML materialization** — :func:`confluid.flow` temporarily swaps the
   active mode to :attr:`ValidationPolicy.yaml` around the ``target(**ctor)``
   call so YAML-driven runs can be configured independently of direct-Python
   instantiation.
3. **MCP tool entrypoints** — navigaitor's subprocess tool bodies call
   :func:`validate_model` on the typed pydantic config before spawning the
   subprocess. Mode comes from :attr:`ValidationPolicy.tool`.

Each mode is one of:

* ``"strict"`` (default) — pydantic ``ValidationError`` is re-raised.
* ``"warn"`` — error is logged via :mod:`logging` and execution continues
  (the downstream code may still fail naturally on the bad value).
* ``"off"`` — validation is skipped entirely; identical to pre-validation
  behaviour.

The policy is process-wide. Defaults to ``("strict", "strict", "strict")``,
overridable via env vars at first :func:`get_policy` access:

* ``CONFLUID_VALIDATE_INIT``
* ``CONFLUID_VALIDATE_YAML``
* ``CONFLUID_VALIDATE_TOOL``

Pydantic is an OPTIONAL dependency (the ``confluid[pydantic]`` extra). When it
is not installed, every validation point degrades to ``"off"`` — a one-time
log line records the downgrade and all three ``validate_*`` functions return
without checking anything.
"""

from __future__ import annotations

import os
from contextlib import contextmanager
from dataclasses import dataclass, replace
from typing import TYPE_CHECKING, Any, Callable, Dict, Iterator, Literal, Optional

from confluid.exceptions import ValidationModeError

if TYPE_CHECKING:
    from pydantic import BaseModel

from loggair import get_logger

logger = get_logger("confluid.validation")

_pydantic_available: Optional[bool] = None


def _have_pydantic() -> bool:
    """True when pydantic is importable; logs a one-time notice when it is not.

    Cached module-wide so the import is attempted (and the downgrade logged)
    at most once per process.
    """
    global _pydantic_available
    if _pydantic_available is None:
        try:
            import pydantic  # noqa: F401

            _pydantic_available = True
        except ImportError:
            _pydantic_available = False
            logger.warning(
                "pydantic is not installed — confluid validation is disabled "
                "(all validation points degrade to 'off'). "
                "Install the extra to enable it: pip install 'confluid[pydantic]'"
            )
    return _pydantic_available


ValidationMode = Literal["strict", "warn", "off"]

_VALID_MODES: frozenset[str] = frozenset(("strict", "warn", "off"))


def _contains_fluid(value: Any, fluid_cls: type) -> bool:
    """Recursively detect whether ``value`` (or any nested element of a
    list / tuple / dict) is a :class:`~confluid.fluid.Fluid` marker.

    Only descends into the three built-in container shapes that confluid's
    YAML loader actually produces — that's enough to catch
    ``stores=[Class(...)]`` (list-of-Fluids), ``data={"train": Class(...)}``
    (dict-of-Fluids), and the various ``tuple``-typed kwargs marainer
    pipelines use. Other custom containers fall back to "concrete" — they
    don't appear in YAML-driven configurations.
    """
    if isinstance(value, fluid_cls):
        return True
    if isinstance(value, list):
        return any(_contains_fluid(v, fluid_cls) for v in value)
    if isinstance(value, tuple):
        return any(_contains_fluid(v, fluid_cls) for v in value)
    if isinstance(value, dict):
        return any(_contains_fluid(v, fluid_cls) for v in value.values())
    return False


@dataclass(frozen=True)
class ValidationPolicy:
    """Strict/warn/off knob per validation point.

    All three default to ``"strict"`` — the safest behaviour for catching bad
    configs early. Use :func:`set_policy` (or env vars) to relax individual
    levels without touching the others.
    """

    init: ValidationMode = "strict"
    yaml: ValidationMode = "strict"
    tool: ValidationMode = "strict"


_policy: Optional[ValidationPolicy] = None


def _normalize_mode(value: str, *, env_var: str) -> ValidationMode:
    """Parse ``value`` to a ``ValidationMode``; raise on unknown literals.

    Used by the env-var reader so a typo (``CONFLUID_VALIDATE_INIT=stict``)
    surfaces loudly at startup rather than being silently treated as
    ``"strict"``.
    """
    lowered = value.strip().lower()
    if lowered not in _VALID_MODES:
        raise ValidationModeError(
            f"{env_var}={value!r} is not a valid ValidationMode " f"(expected one of {sorted(_VALID_MODES)})"
        )
    return lowered  # type: ignore[return-value]


def _policy_from_env() -> ValidationPolicy:
    """Build a :class:`ValidationPolicy` from env vars, falling back to defaults."""
    defaults = ValidationPolicy()
    return ValidationPolicy(
        init=_normalize_mode(os.environ.get("CONFLUID_VALIDATE_INIT", defaults.init), env_var="CONFLUID_VALIDATE_INIT"),
        yaml=_normalize_mode(os.environ.get("CONFLUID_VALIDATE_YAML", defaults.yaml), env_var="CONFLUID_VALIDATE_YAML"),
        tool=_normalize_mode(os.environ.get("CONFLUID_VALIDATE_TOOL", defaults.tool), env_var="CONFLUID_VALIDATE_TOOL"),
    )


def get_policy() -> ValidationPolicy:
    """Return the active :class:`ValidationPolicy` (initialised from env vars on first use)."""
    global _policy
    if _policy is None:
        _policy = _policy_from_env()
    return _policy


def set_policy(
    *,
    init: Optional[ValidationMode] = None,
    yaml: Optional[ValidationMode] = None,
    tool: Optional[ValidationMode] = None,
) -> ValidationPolicy:
    """Replace one or more knobs on the active policy and return the new policy."""
    current = get_policy()
    updates: Dict[str, ValidationMode] = {}
    if init is not None:
        updates["init"] = init
    if yaml is not None:
        updates["yaml"] = yaml
    if tool is not None:
        updates["tool"] = tool
    if not updates:
        return current
    new_policy = replace(current, **updates)
    global _policy
    _policy = new_policy
    return new_policy


def reset_policy() -> None:
    """Drop the cached policy so the next :func:`get_policy` re-reads env vars.

    Intended for tests that mutate env vars and want a clean slate.
    """
    global _policy
    _policy = None


@contextmanager
def override_init_mode(mode: ValidationMode) -> Iterator[None]:
    """Temporarily set :attr:`ValidationPolicy.init` to ``mode``.

    Used by :func:`confluid.flow` to apply :attr:`ValidationPolicy.yaml`
    semantics during YAML materialization without permanently mutating the
    policy.
    """
    previous = get_policy()
    set_policy(init=mode)
    try:
        yield
    finally:
        global _policy
        _policy = previous


def validate_kwargs(cls: Callable[..., Any], kwargs: Dict[str, Any], mode: ValidationMode) -> None:
    """Validate constructor / call kwargs against ``to_pydantic(cls)`` under ``mode``.

    ``cls`` may be a class OR a callable (a ``@configurable`` builder function),
    mirroring ``to_pydantic``'s callable-awareness.

    Builds (or reuses the cached) pydantic mirror of ``cls.__init__`` and
    runs ``Model.model_validate(kwargs)``. On failure:

    * ``"strict"`` — re-raise the pydantic :class:`ValidationError` with a
      message that names ``cls.__name__`` so the user knows which class
      rejected the kwargs.
    * ``"warn"`` — log a warning and return so the wrapped ``__init__`` can
      proceed (it may still fail naturally on the bad value).
    * ``"off"`` — return immediately without building the schema.

    Fluid markers (``Class``, ``Instance``, ``Reference``, ``Lazy``, …) in
    ``kwargs`` represent deferred construction — the live object hasn't been
    built yet, so the pydantic ``is_instance_of(<annotated_type>)`` check
    would always fail. The contract is "validate post-flow": when the Fluid
    materialises via :func:`confluid.flow`, its own ``@configurable``
    ``__init__`` will fire and validate its own kwargs. Fields holding Fluid
    markers are therefore excluded from this call; concrete fields are still
    validated individually so a bad scalar (wrong type, out-of-range int)
    next to a deferred sub-Class still raises here.

    Fluid markers are detected recursively inside ``list`` / ``tuple`` /
    ``dict`` containers — e.g. ``stores=[Class(_Store, …)]`` is a concrete
    list value whose elements are deferred; pydantic would still reject the
    inner ``Class`` marker as ``Input should be an instance of _Store``.
    Any kwarg whose value contains a Fluid anywhere in its tree is treated
    as deferred and skipped.
    """
    if mode == "off" or not _have_pydantic():
        return

    # Lazy import: ``pydantic_export`` pulls pydantic + inspect, which is
    # heavier than this module needs to be eligible to import. ``Fluid`` is
    # imported lazily too so this module stays importable before fluid.py is
    # fully initialised (the loader → fluid → validation chain runs at startup).
    from pydantic import ValidationError

    from confluid.fluid import Fluid
    from confluid.pydantic_export import to_pydantic

    try:
        model = to_pydantic(cls)
    except TypeError:
        # Class signature not introspectable (e.g. C extension without a
        # Python wrapper). Skip validation rather than blocking instantiation.
        return

    # Split kwargs into "concrete" (eager pydantic check) and "deferred"
    # (Fluid markers — skipped here, validated at flow time). Containers
    # holding Fluids count as deferred — a ``list[Store]`` populated with
    # ``Class`` markers would otherwise trip ``is_instance_of(Store)`` on
    # the inner element. See the regression cluster in
    # ``tests/test_validation.py::test_fluid_kwarg_nested_in_list``.
    concrete = {k: v for k, v in kwargs.items() if not _contains_fluid(v, Fluid)}
    deferred_keys = set(kwargs) - set(concrete)

    if not concrete:
        # Whole call is deferred — nothing to check now. The flow() pass that
        # materialises each Fluid will revalidate at that point.
        return

    try:
        if not deferred_keys:
            # Fast path: every kwarg is concrete, validate the whole model in
            # one shot (catches model-level cross-field validators too).
            model.model_validate(kwargs)
        else:
            # Mixed: validate concrete kwargs field-by-field so the
            # deferred-Fluid fields don't trigger "is_instance_of" failures
            # nor "field required" errors. ``validate_assignment`` checks one
            # field against the model's schema; ``model_construct`` builds an
            # un-validated stub instance to give it a target.
            stub = model.model_construct()
            for name, value in concrete.items():
                if name not in model.model_fields:
                    continue
                model.__pydantic_validator__.validate_assignment(stub, name, value)
    except ValidationError as exc:
        if mode == "strict":
            raise
        logger.warning(f"{cls.__name__}: invalid configuration\n{exc}")


def validate_setattr(cls: type, name: str, value: Any, mode: ValidationMode) -> Optional[str]:
    """Validate a post-construction setattr against the field's pydantic type.

    Mirrors :func:`validate_kwargs` for the single-field case used by
    :func:`confluid.configure`. Unknown field names are silently allowed
    here (the configure path may target attributes outside the ``__init__``
    signature, e.g. ``@configurable`` classes that expose extra knobs as
    plain instance attributes).

    Returns:
        The stringified validation error on a WARN-mode failure (so the
        caller can record it in a ``ConfigurationReport``), ``None`` on
        pass / off / unknown field. Strict mode still raises.
    """
    if mode == "off" or not _have_pydantic():
        return None

    from pydantic import ValidationError

    from confluid.pydantic_export import to_pydantic

    try:
        model = to_pydantic(cls)
    except TypeError:
        return None

    if name not in model.model_fields:
        return None

    try:
        model.__pydantic_validator__.validate_assignment(model.model_construct(), name, value)
    except ValidationError as exc:
        if mode == "strict":
            raise
        logger.warning(f"{cls.__name__}.{name}: invalid value\n{exc}")
        return str(exc)
    return None


def validate_model(model: BaseModel, mode: ValidationMode) -> None:
    """Re-validate an already-constructed pydantic model under ``mode``.

    Pydantic validates at construction, but navigaitor's MCP tool entry needs
    to surface ``warn`` outcomes as structured warnings without raising. This
    helper redundantly re-validates so the same mode logic applies uniformly.
    """
    if mode == "off" or not _have_pydantic():
        return

    from pydantic import ValidationError

    try:
        type(model).model_validate(model.model_dump())
    except ValidationError as exc:
        if mode == "strict":
            raise
        logger.warning(f"{type(model).__name__}: invalid configuration\n{exc}")


__all__ = [
    "ValidationMode",
    "ValidationPolicy",
    "get_policy",
    "set_policy",
    "reset_policy",
    "override_init_mode",
    "validate_kwargs",
    "validate_setattr",
    "validate_model",
]
